### ISSUE TITLE
비밀번호를 틀리면..?

### ISSUE THREAD

**Issue by GGos3** [tempfiles-Team/tempfiles-frontend#72] opened 2022-11-15 16:23 UTC
![Screenshot_20221116-012236_Chrome](https://user-images.githubusercontent.com/84070816/201972068-f186de23-e606-4849-b755-0666d4c6ae65.jpg)
오우 이렇게 되는군요

**Comment by minpeter** [comment] 2022-11-15 16:25
Duplicate of #71

**Closed** 2022-11-15 16:25 UTC
