### ISSUE TITLE
업로드 성공!

### ISSUE THREAD

**Issue by GGos3** [tempfiles-Team/tempfiles-frontend#73] opened 2022-11-15 16:25 UTC
![Screenshot_20221116-012448_Chrome](https://user-images.githubusercontent.com/84070816/201972555-b38b4f0d-0578-4cb8-a6cd-ff785e9afb50.jpg)
W0W

**Comment by minpeter** [comment] 2022-11-15 16:25
Duplicate of #71

**Closed by minpeter** 2022-11-15 16:25 UTC
